import { PostalCode } from "@/interfaces/interfaces";

const POSTAL_CODE: PostalCode[] = [
    // Puerto Vallarta
    { id: '1', stablishment_name: '12 de Octubre', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '2', stablishment_name: '24 de Febrero', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '3', stablishment_name: '5 de Diciembre', postal_code: '48350', municipality: 'Puerto Vallarta' },
    { id: '4', stablishment_name: '9 de Octubre', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '5', stablishment_name: 'Aeropuerto', postal_code: '48317', municipality: 'Puerto Vallarta' },
    { id: '6', stablishment_name: 'Agua Azul', postal_code: '48340', municipality: 'Puerto Vallarta' },
    { id: '7', stablishment_name: 'Agua Zarca', postal_code: '48315', municipality: 'Puerto Vallarta' },
    { id: '8', stablishment_name: 'Albatros', postal_code: '48315', municipality: 'Puerto Vallarta' },
    { id: '9', stablishment_name: 'Altavista', postal_code: '48380', municipality: 'Puerto Vallarta' },
    { id: '10', stablishment_name: 'Amapas', postal_code: '48399', municipality: 'Puerto Vallarta' },
    { id: '11', stablishment_name: 'Ampliación Vista Dorada', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '12', stablishment_name: 'Ampliación Vista Hermosa', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '13', stablishment_name: 'Andalucía', postal_code: '48291', municipality: 'Puerto Vallarta' },
    { id: '14', stablishment_name: 'Aramara', postal_code: '48314', municipality: 'Puerto Vallarta' },
    { id: '15', stablishment_name: 'Arboledas', postal_code: '48315', municipality: 'Puerto Vallarta' },
    { id: '16', stablishment_name: 'Balcones Vallarta', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '17', stablishment_name: 'Banús Vallarta', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '18', stablishment_name: 'Benito Juárez', postal_code: '48389', municipality: 'Puerto Vallarta' },
    { id: '19', stablishment_name: 'Bobadilla', postal_code: '48298', municipality: 'Puerto Vallarta' },
    { id: '20', stablishment_name: 'Boca de Tomatlán', postal_code: '48292', municipality: 'Puerto Vallarta' },
    { id: '21', stablishment_name: 'Bocanegra', postal_code: '48335', municipality: 'Puerto Vallarta' },
    { id: '22', stablishment_name: 'Bosque del Progreso', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '23', stablishment_name: 'Brisas del Pacifico', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '24', stablishment_name: 'Buenos Aires', postal_code: '48370', municipality: 'Puerto Vallarta' },
    { id: '25', stablishment_name: 'Bugambilias', postal_code: '48340', municipality: 'Puerto Vallarta' },
    { id: '26', stablishment_name: 'C.U.C.', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '27', stablishment_name: 'Campestre Las Cañadas', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '28', stablishment_name: 'Campestre las Palmas', postal_code: '48343', municipality: 'Puerto Vallarta' },
    { id: '29', stablishment_name: 'Campestre San Nicolás', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '30', stablishment_name: 'Campo Verde', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '31', stablishment_name: 'Centro de Salud', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '32', stablishment_name: 'Club de Golf Vista Vallarta', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '33', stablishment_name: 'Coapinole', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '34', stablishment_name: 'Colina Universitaria', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '35', stablishment_name: 'Colinas de la Bahía', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '36', stablishment_name: 'Colinas del Valle', postal_code: '48284', municipality: 'Puerto Vallarta' },
    { id: '37', stablishment_name: 'Conchas Chinas', postal_code: '48399', municipality: 'Puerto Vallarta' },
    { id: '38', stablishment_name: 'Copa del Rey', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '39', stablishment_name: 'Costa Dorada', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '40', stablishment_name: 'Cristóbal Colon', postal_code: '48327', municipality: 'Puerto Vallarta' },
    { id: '41', stablishment_name: 'De las Juntas Delegación', postal_code: '48291', municipality: 'Puerto Vallarta' },
    { id: '42', stablishment_name: 'Del Mar', postal_code: '48344', municipality: 'Puerto Vallarta' },
    { id: '43', stablishment_name: 'Del Toro', postal_code: '48296', municipality: 'Puerto Vallarta' },
    { id: '44', stablishment_name: 'Del Villar', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '45', stablishment_name: 'Delfines', postal_code: '48325', municipality: 'Puerto Vallarta' },
    { id: '46', stablishment_name: 'Díaz Ordaz', postal_code: '48310', municipality: 'Puerto Vallarta' },
    { id: '47', stablishment_name: 'Ébano', postal_code: '48291', municipality: 'Puerto Vallarta' },
    { id: '48', stablishment_name: 'Ecoterra', postal_code: '48284', municipality: 'Puerto Vallarta' },
    { id: '49', stablishment_name: 'Educación', postal_code: '48338', municipality: 'Puerto Vallarta' },
    { id: '50', stablishment_name: 'El Caloso', postal_code: '48360', municipality: 'Puerto Vallarta' },
    { id: '51', stablishment_name: 'El Calvario', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '52', stablishment_name: 'El Cantón', postal_code: '48284', municipality: 'Puerto Vallarta' },
    { id: '53', stablishment_name: 'El Carmen', postal_code: '48338', municipality: 'Puerto Vallarta' },
    { id: '54', stablishment_name: 'El Cerro', postal_code: '48304', municipality: 'Puerto Vallarta' },
    { id: '55', stablishment_name: 'El Colorado', postal_code: '48265', municipality: 'Puerto Vallarta' },
    { id: '56', stablishment_name: 'El Conejo', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '57', stablishment_name: 'El Crucero', postal_code: '48291', municipality: 'Puerto Vallarta' },
    { id: '58', stablishment_name: 'El Mangal', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '59', stablishment_name: 'El Nogalito', postal_code: '48399', municipality: 'Puerto Vallarta' },
    { id: '60', stablishment_name: 'El Palmar de Aramara', postal_code: '48314', municipality: 'Puerto Vallarta' },
    { id: '61', stablishment_name: 'El Palmar del Progreso', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '62', stablishment_name: 'El Paso Real', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '63', stablishment_name: 'El Ranchito (El Colesio)', postal_code: '48283', municipality: 'Puerto Vallarta' },
    { id: '64', stablishment_name: 'El Remance', postal_code: '48389', municipality: 'Puerto Vallarta' },
    { id: '65', stablishment_name: 'El Salitrillo', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '66', stablishment_name: 'El Zancudo', postal_code: '48265', municipality: 'Puerto Vallarta' },
    { id: '67', stablishment_name: 'Emiliano Zapata', postal_code: '48380', municipality: 'Puerto Vallarta' },
    { id: '68', stablishment_name: 'FOVISSSTE 100', postal_code: '48313', municipality: 'Puerto Vallarta' },
    { id: '69', stablishment_name: 'Fovissste 96', postal_code: '48328', municipality: 'Puerto Vallarta' },
    { id: '70', stablishment_name: 'Garza Blanca', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '71', stablishment_name: 'Gastronómicos', postal_code: '48353', municipality: 'Puerto Vallarta' },
    { id: '72', stablishment_name: 'Gaviotas', postal_code: '48328', municipality: 'Puerto Vallarta' },
    { id: '73', stablishment_name: 'Getsemaní', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '74', stablishment_name: 'Guadalupe Victoria', postal_code: '48317', municipality: 'Puerto Vallarta' },
    { id: '75', stablishment_name: 'Haciendas Del Pitilla', postal_code: '48318', municipality: 'Puerto Vallarta' },
    { id: '76', stablishment_name: 'Héroes de La Patria', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '77', stablishment_name: 'Herradura', postal_code: '48340', municipality: 'Puerto Vallarta' },
    { id: '78', stablishment_name: 'Hipódromo', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '79', stablishment_name: 'Ignacio L Vallarta', postal_code: '48325', municipality: 'Puerto Vallarta' },
    { id: '80', stablishment_name: 'Independencia', postal_code: '48327', municipality: 'Puerto Vallarta' },
    { id: '81', stablishment_name: 'INFONAVIT CTM', postal_code: '48318', municipality: 'Puerto Vallarta' },
    { id: '82', stablishment_name: 'Ixtapa', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '83', stablishment_name: 'Ixtapa Centro', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '84', stablishment_name: 'Jade', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '85', stablishment_name: 'Jardines', postal_code: '48344', municipality: 'Puerto Vallarta' },
    { id: '86', stablishment_name: 'Jardines', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '87', stablishment_name: 'Jardines de La Higuera', postal_code: '48313', municipality: 'Puerto Vallarta' },
    { id: '88', stablishment_name: 'Jardines de Vallarta', postal_code: '48328', municipality: 'Puerto Vallarta' },
    { id: '89', stablishment_name: 'Jardines Del Puerto', postal_code: '48315', municipality: 'Puerto Vallarta' },
    { id: '90', stablishment_name: 'Joyas del Colorado', postal_code: '48284', municipality: 'Puerto Vallarta' },
    { id: '91', stablishment_name: 'Joyas del Pedregal', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '92', stablishment_name: 'La Arboleda (Lomas del Valle)', postal_code: '48284', municipality: 'Puerto Vallarta' },
    { id: '93', stablishment_name: 'La Aurora', postal_code: '48338', municipality: 'Puerto Vallarta' },
    { id: '94', stablishment_name: 'La Calma', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '95', stablishment_name: 'La Colonia', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '96', stablishment_name: 'La Desembocada', postal_code: '48283', municipality: 'Puerto Vallarta' },
    { id: '97', stablishment_name: 'La Esperanza', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '98', stablishment_name: 'La Floresta', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '99', stablishment_name: 'La Joya', postal_code: '48314', municipality: 'Puerto Vallarta' },
    { id: '100', stablishment_name: 'La Marina', postal_code: '48314', municipality: 'Puerto Vallarta' },
    { id: '101', stablishment_name: 'La Mesa del Veladero', postal_code: '48264', municipality: 'Puerto Vallarta' },
    { id: '102', stablishment_name: 'La Mina', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '103', stablishment_name: 'La Mina II', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '104', stablishment_name: 'La Moderna', postal_code: '48344', municipality: 'Puerto Vallarta' },
    { id: '105', stablishment_name: 'La Pedrera', postal_code: '48343', municipality: 'Puerto Vallarta' },
    { id: '106', stablishment_name: 'La Playita', postal_code: '48296', municipality: 'Puerto Vallarta' },
    { id: '107', stablishment_name: 'La Primavera', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '108', stablishment_name: 'La Trinidad', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '109', stablishment_name: 'La Vena', postal_code: '48320', municipality: 'Puerto Vallarta' },
    { id: '110', stablishment_name: 'La Vía', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '111', stablishment_name: 'Laguna del Valle', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '112', stablishment_name: 'Las Aralias', postal_code: '48328', municipality: 'Puerto Vallarta' },
    { id: '113', stablishment_name: 'Las Canoas', postal_code: '48360', municipality: 'Puerto Vallarta' },
    { id: '114', stablishment_name: 'Las Flores', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '115', stablishment_name: 'Las Glorias', postal_code: '48333', municipality: 'Puerto Vallarta' },
    { id: '116', stablishment_name: 'Las Higueras del Hundido', postal_code: '48276', municipality: 'Puerto Vallarta' },
    { id: '117', stablishment_name: 'Las Mojoneras', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '118', stablishment_name: 'Las Moras', postal_code: '48315', municipality: 'Puerto Vallarta' },
    { id: '119', stablishment_name: 'Las Palmas de Arriba', postal_code: '48260', municipality: 'Puerto Vallarta' },
    { id: '120', stablishment_name: 'Las Peñas', postal_code: '48360', municipality: 'Puerto Vallarta' },
    { id: '121', stablishment_name: 'Lázaro Cárdenas', postal_code: '48330', municipality: 'Puerto Vallarta' },
    { id: '122', stablishment_name: 'Leandro Valle', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '123', stablishment_name: 'Linda Vista Océano', postal_code: '48344', municipality: 'Puerto Vallarta' },
    { id: '124', stablishment_name: 'Lisboa', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '125', stablishment_name: 'Llanitos', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '126', stablishment_name: 'Loma Bonita', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '127', stablishment_name: 'Loma Bonita', postal_code: '48291', municipality: 'Puerto Vallarta' },
    { id: '128', stablishment_name: 'Lomas de Coapinole', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '129', stablishment_name: 'Lomas de Enmedio', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '130', stablishment_name: 'Lomas de San Nicolás', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '131', stablishment_name: 'Lomas Del Calvario', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '132', stablishment_name: 'Lomas Del Pedregal', postal_code: '48343', municipality: 'Puerto Vallarta' },
    { id: '133', stablishment_name: 'Lomas del Progreso', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '134', stablishment_name: 'López Mateos', postal_code: '48340', municipality: 'Puerto Vallarta' },
    { id: '135', stablishment_name: 'Los Ángeles', postal_code: '48284', municipality: 'Puerto Vallarta' },
    { id: '136', stablishment_name: 'Los Cipreses', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '137', stablishment_name: 'Los Llanitos', postal_code: '48267', municipality: 'Puerto Vallarta' },
    { id: '138', stablishment_name: 'Los Llanitos', postal_code: '48276', municipality: 'Puerto Vallarta' },
    { id: '139', stablishment_name: 'Los Mangos', postal_code: '48310', municipality: 'Puerto Vallarta' },
    { id: '140', stablishment_name: 'Los Médanos', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '141', stablishment_name: 'Los Portales', postal_code: '48315', municipality: 'Puerto Vallarta' },
    { id: '142', stablishment_name: 'Los Robles', postal_code: '48373', municipality: 'Puerto Vallarta' },
    { id: '143', stablishment_name: 'Los Sauces', postal_code: '48328', municipality: 'Puerto Vallarta' },
    { id: '144', stablishment_name: 'Los Tamarindos', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '145', stablishment_name: 'Los Tules', postal_code: '48333', municipality: 'Puerto Vallarta' },
    { id: '146', stablishment_name: 'Magisterio', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '147', stablishment_name: 'Magnolias Residencial', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '148', stablishment_name: 'Maralta', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '149', stablishment_name: 'Maravillas Vallarta', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '150', stablishment_name: 'Mariano Otero', postal_code: '48320', municipality: 'Puerto Vallarta' },
    { id: '151', stablishment_name: 'Marina Sol', postal_code: '48334', municipality: 'Puerto Vallarta' },
    { id: '152', stablishment_name: 'Marina Vallarta', postal_code: '48335', municipality: 'Puerto Vallarta' },
    { id: '153', stablishment_name: 'Mismaloya', postal_code: '48294', municipality: 'Puerto Vallarta' },
    { id: '154', stablishment_name: 'Montesori', postal_code: '48314', municipality: 'Puerto Vallarta' },
    { id: '155', stablishment_name: 'Morelos y Pavón', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '156', stablishment_name: 'Niños Héroes', postal_code: '48325', municipality: 'Puerto Vallarta' },
    { id: '157', stablishment_name: 'Niños Héroes', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '158', stablishment_name: 'Nuevo Ixtapa', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '159', stablishment_name: 'Ojo de Agua', postal_code: '48344', municipality: 'Puerto Vallarta' },
    { id: '160', stablishment_name: 'Ojo de Agua', postal_code: '48284', municipality: 'Puerto Vallarta' },
    { id: '161', stablishment_name: 'Olímpica', postal_code: '48330', municipality: 'Puerto Vallarta' },
    { id: '162', stablishment_name: 'Pacífico Azul', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '163', stablishment_name: 'Palma Real', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '164', stablishment_name: 'Palmar de Ixtapa', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '165', stablishment_name: 'Palmares Universidad', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '166', stablishment_name: 'Paraíso', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '167', stablishment_name: 'Parques las Palmas', postal_code: '48317', municipality: 'Puerto Vallarta' },
    { id: '168', stablishment_name: 'Parques Universidad (Sendero de Luna)', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '169', stablishment_name: 'Paseos de La Ribera', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '170', stablishment_name: 'Paseos Universidad', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '171', stablishment_name: 'Paseos Universidad II', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '172', stablishment_name: 'Paso Ancho', postal_code: '48373', municipality: 'Puerto Vallarta' },
    { id: '173', stablishment_name: 'Paso del Guayabo', postal_code: '48373', municipality: 'Puerto Vallarta' },
    { id: '174', stablishment_name: 'Paso Del Molino', postal_code: '48373', municipality: 'Puerto Vallarta' },
    { id: '175', stablishment_name: 'Pitillal Centro', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '176', stablishment_name: 'Playa Grande (San Pedro)', postal_code: '48327', municipality: 'Puerto Vallarta' },
    { id: '177', stablishment_name: 'Prados de la Higuera', postal_code: '48313', municipality: 'Puerto Vallarta' },
    { id: '178', stablishment_name: 'Prados de la Montaña', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '179', stablishment_name: 'Presidentes Municipales', postal_code: '48344', municipality: 'Puerto Vallarta' },
    { id: '180', stablishment_name: 'Primavera', postal_code: '48325', municipality: 'Puerto Vallarta' },
    { id: '181', stablishment_name: 'Primavera de Vallarta', postal_code: '48313', municipality: 'Puerto Vallarta' },
    { id: '182', stablishment_name: 'Primero de Mayo', postal_code: '48325', municipality: 'Puerto Vallarta' },
    { id: '183', stablishment_name: 'Primero de Mayo', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '184', stablishment_name: 'Progreso', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '185', stablishment_name: 'Puerta del Sol Residencial', postal_code: '48314', municipality: 'Puerto Vallarta' },
    { id: '186', stablishment_name: 'Puerto Iguanas', postal_code: '48334', municipality: 'Puerto Vallarta' },
    { id: '187', stablishment_name: 'Puerto Vallarta (Licenciado Gustavo Díaz Ordaz)', postal_code: '48339', municipality: 'Puerto Vallarta' },
    { id: '188', stablishment_name: 'Puerto Vallarta Centro', postal_code: '48300', municipality: 'Puerto Vallarta' },
    { id: '189', stablishment_name: 'Ramblases', postal_code: '48343', municipality: 'Puerto Vallarta' },
    { id: '190', stablishment_name: 'Rancho Alegre', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '191', stablishment_name: 'Rancho Nácar', postal_code: '48284', municipality: 'Puerto Vallarta' },
    { id: '192', stablishment_name: 'Real Ixtapa', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '193', stablishment_name: 'Residencial Fluvial Vallarta', postal_code: '48312', municipality: 'Puerto Vallarta' },
    { id: '194', stablishment_name: 'Rincón del Puerto', postal_code: '48317', municipality: 'Puerto Vallarta' },
    { id: '195', stablishment_name: 'San Esteban', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '196', stablishment_name: 'San Francisco', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '197', stablishment_name: 'San José', postal_code: '48291', municipality: 'Puerto Vallarta' },
    { id: '198', stablishment_name: 'San Miguel', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '199', stablishment_name: 'San Nicolás', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '200', stablishment_name: 'Santa Cruz de Quelitán (Palmillas)', postal_code: '48266', municipality: 'Puerto Vallarta' },
    { id: '201', stablishment_name: 'Santa Maria', postal_code: '48325', municipality: 'Puerto Vallarta' },
    { id: '202', stablishment_name: 'Santa Maria', postal_code: '48344', municipality: 'Puerto Vallarta' },
    { id: '203', stablishment_name: 'Santo Domingo', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '204', stablishment_name: 'Sendero del Parque', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '205', stablishment_name: 'Sendero las Galeanas', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '206', stablishment_name: 'Sierra del Mar', postal_code: '48294', municipality: 'Puerto Vallarta' },
    { id: '207', stablishment_name: 'Tabachines', postal_code: '48314', municipality: 'Puerto Vallarta' },
    { id: '208', stablishment_name: 'Tebelchia (El Roble)', postal_code: '48262', municipality: 'Puerto Vallarta' },
    { id: '209', stablishment_name: 'Terminal Marítima', postal_code: '48333', municipality: 'Puerto Vallarta' },
    { id: '210', stablishment_name: 'Valentín Gómez Farias', postal_code: '48320', municipality: 'Puerto Vallarta' },
    { id: '211', stablishment_name: 'Vallarta 500', postal_code: '48315', municipality: 'Puerto Vallarta' },
    { id: '212', stablishment_name: 'Vallarta 750', postal_code: '48314', municipality: 'Puerto Vallarta' },
    { id: '213', stablishment_name: 'Vallarta Villas', postal_code: '48313', municipality: 'Puerto Vallarta' },
    { id: '214', stablishment_name: 'Valle del Mar', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '215', stablishment_name: 'Valle Dorado', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '216', stablishment_name: 'Verde Vallarta', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '217', stablishment_name: 'Verde Valle', postal_code: '48265', municipality: 'Puerto Vallarta' },
    { id: '218', stablishment_name: 'Versalles', postal_code: '48310', municipality: 'Puerto Vallarta' },
    { id: '219', stablishment_name: 'Vida Vallarta', postal_code: '48318', municipality: 'Puerto Vallarta' },
    { id: '220', stablishment_name: 'Villa de Guadalupe', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '221', stablishment_name: 'Villa las Flores', postal_code: '48335', municipality: 'Puerto Vallarta' },
    { id: '222', stablishment_name: 'Villa Paradiso', postal_code: '48291', municipality: 'Puerto Vallarta' },
    { id: '223', stablishment_name: 'Villas del Mar', postal_code: '48315', municipality: 'Puerto Vallarta' },
    { id: '224', stablishment_name: 'Villas del Prado', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '225', stablishment_name: 'Villas Del Puerto', postal_code: '48315', municipality: 'Puerto Vallarta' },
    { id: '226', stablishment_name: 'Villas del Real', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '227', stablishment_name: 'Villas Ixtapa', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '228', stablishment_name: 'Villas las Juntas', postal_code: '48291', municipality: 'Puerto Vallarta' },
    { id: '229', stablishment_name: 'Villas Las Palmas', postal_code: '48291', municipality: 'Puerto Vallarta' },
    { id: '230', stablishment_name: 'Villas Primavera', postal_code: '48338', municipality: 'Puerto Vallarta' },
    { id: '231', stablishment_name: 'Villas Rio', postal_code: '48313', municipality: 'Puerto Vallarta' },
    { id: '232', stablishment_name: 'Villas Sol', postal_code: '48315', municipality: 'Puerto Vallarta' },
    { id: '233', stablishment_name: 'Villas Universidad', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '234', stablishment_name: 'Vista al Mar', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '235', stablishment_name: 'Vista Dorada', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '236', stablishment_name: 'Vista Hermosa', postal_code: '48280', municipality: 'Puerto Vallarta' },
    { id: '237', stablishment_name: 'Vista Hermosa II', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '238', stablishment_name: 'Volcanes', postal_code: '48290', municipality: 'Puerto Vallarta' },
    { id: '239', stablishment_name: 'Zona Hotelera Norte', postal_code: '48333', municipality: 'Puerto Vallarta' },
    { id: '240', stablishment_name: 'Zona Hotelera Sur', postal_code: '48333', municipality: 'Puerto Vallarta' },
    { id: '241', stablishment_name: 'Zyan', postal_code: '48291', municipality: 'Puerto Vallarta' },

    // Bahía de Banderas
    { id: '242', stablishment_name: '13 de Septiembre', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '243', stablishment_name: 'Agave Azul', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '244', stablishment_name: 'Aguamilpa', postal_code: '63739', municipality: 'Bahía de Banderas' },
    { id: '245', stablishment_name: 'Aldea Hortus', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '246', stablishment_name: 'Altavela', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '247', stablishment_name: 'Arboledas- Bahia de banderas', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '248', stablishment_name: 'Arcos de San José', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '249', stablishment_name: 'Azul Turquesa', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '250', stablishment_name: 'Bahía Azul', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '251', stablishment_name: 'Bahía de Banderas', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '252', stablishment_name: 'Bicentenario', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '253', stablishment_name: 'Bucerías Centro', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '254', stablishment_name: 'Buenos Aires', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '255', stablishment_name: 'Bugambilias - Bahia banderas', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '256', stablishment_name: 'Colibrí', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '257', stablishment_name: 'Concepción de Valle', postal_code: '63738', municipality: 'Bahía de Banderas' },
    { id: '258', stablishment_name: 'Corral del Risco (Punta de Mita)', postal_code: '63734', municipality: 'Bahía de Banderas' },
    { id: '259', stablishment_name: 'Costa Coral', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '260', stablishment_name: 'Cruz de Huanacaxtle', postal_code: '63734', municipality: 'Bahía de Banderas' },
    { id: '261', stablishment_name: 'Cumbres', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '262', stablishment_name: 'Del Lago Residencial', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '263', stablishment_name: 'Deportiva', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '264', stablishment_name: 'Diana Laura', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '265', stablishment_name: 'Dorada', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '266', stablishment_name: 'El Carrizo', postal_code: '63739', municipality: 'Bahía de Banderas' },
    { id: '267', stablishment_name: 'El Coatante', postal_code: '63739', municipality: 'Bahía de Banderas' },
    { id: '268', stablishment_name: 'El Colomo', postal_code: '63736', municipality: 'Bahía de Banderas' },
    { id: '269', stablishment_name: 'El Guamúchil', postal_code: '63726', municipality: 'Bahía de Banderas' },
    { id: '270', stablishment_name: 'El Manglar', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '271', stablishment_name: 'El Mirador', postal_code: '63730', municipality: 'Bahía de Banderas' },
    { id: '272', stablishment_name: 'El Palmar', postal_code: '63738', municipality: 'Bahía de Banderas' },
    { id: '273', stablishment_name: 'El Parque', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '274', stablishment_name: 'El Porvenir', postal_code: '63738', municipality: 'Bahía de Banderas' },
    { id: '275', stablishment_name: 'El Quelele', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '276', stablishment_name: 'El Rastro', postal_code: '63730', municipality: 'Bahía de Banderas' },
    { id: '277', stablishment_name: 'El Rastro', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '278', stablishment_name: 'El Roble', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '279', stablishment_name: 'Emilio M. González', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '280', stablishment_name: 'Ex-Hacienda San Ángel', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '281', stablishment_name: 'Flamingos', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '282', stablishment_name: 'Fortuna de Vallejo (La Gloria)', postal_code: '63739', municipality: 'Bahía de Banderas' },
    { id: '283', stablishment_name: 'Francisco Javier Ovando', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '284', stablishment_name: 'Habitat La Concha', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '285', stablishment_name: 'Haciendas de San Vicente', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '286', stablishment_name: 'Higuera Blanca', postal_code: '63734', municipality: 'Bahía de Banderas' },
    { id: '287', stablishment_name: 'Jardín las Arboledas', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '288', stablishment_name: 'Jardines de San José', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '289', stablishment_name: 'Jardines del Sol', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '290', stablishment_name: 'Jardines El Porvenir', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '291', stablishment_name: 'José Chávez', postal_code: '63734', municipality: 'Bahía de Banderas' },
    { id: '292', stablishment_name: 'La Entrada', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '293', stablishment_name: 'La Fronda', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '294', stablishment_name: 'La Lomita', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '295', stablishment_name: 'La Misión', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '296', stablishment_name: 'La Noria', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '297', stablishment_name: 'La Nueva Aurora', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '298', stablishment_name: 'La Primavera', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '299', stablishment_name: 'La Primavera', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '300', stablishment_name: 'La Reserva Residencial', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '301', stablishment_name: 'La Unidad', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '302', stablishment_name: 'Las Brisas', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '303', stablishment_name: 'Las Ceibas', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '304', stablishment_name: 'Las Flores', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '305', stablishment_name: 'Las Hachas', postal_code: '63730', municipality: 'Bahía de Banderas' },
    { id: '306', stablishment_name: 'Las Jarretaderas', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '307', stablishment_name: 'Las Palmas', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '308', stablishment_name: 'Las Parotas', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '309', stablishment_name: 'Las Villas', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '310', stablishment_name: 'Lázaro Cárdenas', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '311', stablishment_name: 'Lo de Marcos', postal_code: '63729', municipality: 'Bahía de Banderas' },
    { id: '312', stablishment_name: 'Loma Bonita', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '313', stablishment_name: 'Lomas del Sol', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '314', stablishment_name: 'Lomas Huanacaxtle', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '315', stablishment_name: 'Los Ángeles', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '316', stablishment_name: 'Los Arboles', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '317', stablishment_name: 'Los Encantos', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '318', stablishment_name: 'Los Mangos', postal_code: '63738', municipality: 'Bahía de Banderas' },
    { id: '319', stablishment_name: 'Los Palmares San Vicente', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '320', stablishment_name: 'Los Sauces', postal_code: '63739', municipality: 'Bahía de Banderas' },
    { id: '321', stablishment_name: 'Mezcales', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '322', stablishment_name: 'Mezcalitos', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '323', stablishment_name: 'Monte Calvario', postal_code: '63734', municipality: 'Bahía de Banderas' },
    { id: '324', stablishment_name: 'Nueva Era', postal_code: '63734', municipality: 'Bahía de Banderas' },
    { id: '325', stablishment_name: 'Nuevo San Clemente', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '326', stablishment_name: 'Nuevo Vallarta', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '327', stablishment_name: 'Palma Real', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '328', stablishment_name: 'Palma Residencial', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '329', stablishment_name: 'Paraíso del Indio', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '330', stablishment_name: 'Paraíso Vallarta', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '331', stablishment_name: 'Playas de Huanacaxtle', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '332', stablishment_name: 'Playas del Pacífico', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '333', stablishment_name: 'Portovela', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '334', stablishment_name: 'Primavera Residencial', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '335', stablishment_name: 'Puerta del Mar', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '336', stablishment_name: 'Punta de Mita', postal_code: '63734', municipality: 'Bahía de Banderas' },
    { id: '337', stablishment_name: 'Ramón Larios', postal_code: '63730', municipality: 'Bahía de Banderas' },
    { id: '338', stablishment_name: 'Real Nuevo Vallarta', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '339', stablishment_name: 'Refugio Laguna', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '340', stablishment_name: 'Residencial Los Mangos', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '341', stablishment_name: 'Rincón del Cielo', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '342', stablishment_name: 'Rinconada de Banderas', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '343', stablishment_name: 'Rinconada Las Flores', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '344', stablishment_name: 'San Clemente de Lima', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '345', stablishment_name: 'San Francisco', postal_code: '63729', municipality: 'Bahía de Banderas' },
    { id: '346', stablishment_name: 'San Ignacio', postal_code: '63728', municipality: 'Bahía de Banderas' },
    { id: '347', stablishment_name: 'San Isidro', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '348', stablishment_name: 'San José', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '349', stablishment_name: 'San José del Valle', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '350', stablishment_name: 'San Juan de Abajo', postal_code: '63730', municipality: 'Bahía de Banderas' },
    { id: '351', stablishment_name: 'San Quintín', postal_code: '63728', municipality: 'Bahía de Banderas' },
    { id: '352', stablishment_name: 'San Vicente', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '353', stablishment_name: 'San Vicente', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '354', stablishment_name: 'San Vicente del Mar', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '355', stablishment_name: 'Santa Fe', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '356', stablishment_name: 'Santa Rosa Tapachula', postal_code: '63730', municipality: 'Bahía de Banderas' },
    { id: '357', stablishment_name: 'Sayulita', postal_code: '63734', municipality: 'Bahía de Banderas' },
    { id: '358', stablishment_name: 'Tabacalera', postal_code: '63730', municipality: 'Bahía de Banderas' },
    { id: '359', stablishment_name: 'Terralta', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '360', stablishment_name: 'Tondoroque', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '361', stablishment_name: 'Toscano', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '362', stablishment_name: 'Tule Dorado', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '363', stablishment_name: 'Tulipanes', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '364', stablishment_name: 'Valle de Banderas', postal_code: '63730', municipality: 'Bahía de Banderas' },
    { id: '365', stablishment_name: 'Valle de la Guadalupana', postal_code: '63730', municipality: 'Bahía de Banderas' },
    { id: '366', stablishment_name: 'Valle de San José', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '367', stablishment_name: 'Valle Dorado', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '368', stablishment_name: 'Valle Esmeralda', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '369', stablishment_name: 'Valle Marlín', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '370', stablishment_name: 'Vilanova', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '371', stablishment_name: 'Villa Esmeralda', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '372', stablishment_name: 'Villas de Banderas', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '373', stablishment_name: 'Villas de La Bahía', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '374', stablishment_name: 'Villas de San Vicente', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '375', stablishment_name: 'Villas Green Canal', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '376', stablishment_name: 'Villas las Parotas', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '377', stablishment_name: 'Villas Miramar', postal_code: '63737', municipality: 'Bahía de Banderas' },
    { id: '378', stablishment_name: 'Villas Vallarta', postal_code: '63735', municipality: 'Bahía de Banderas' },
    { id: '379', stablishment_name: 'Virreyes Vallarta', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '380', stablishment_name: 'Vista Bahía', postal_code: '63732', municipality: 'Bahía de Banderas' },
    { id: '381', stablishment_name: 'Zitadela', postal_code: '63735', municipality: 'Bahía de Banderas' },

    // Cabo Corrientes
    { id: '382', stablishment_name: 'Aquiles Serdán', postal_code: '48417', municipality: 'Cabo corrientes' },
    { id: '383', stablishment_name: 'Bioto', postal_code: '48433', municipality: 'Cabo corrientes' },
    { id: '384', stablishment_name: 'Chacala', postal_code: '48427', municipality: 'Cabo corrientes' },
    { id: '385', stablishment_name: 'Chimo', postal_code: '48415', municipality: 'Cabo corrientes' },
    { id: '386', stablishment_name: 'El Columpio', postal_code: '48426', municipality: 'Cabo corrientes' },
    { id: '387', stablishment_name: 'El Refugio Suchitlán (La Congregación)', postal_code: '48420', municipality: 'Cabo corrientes' },
    { id: '388', stablishment_name: 'El Rincón de los Olotes (El Rincón)', postal_code: '48447', municipality: 'Cabo corrientes' },
    { id: '389', stablishment_name: 'El Tuito', postal_code: '48400', municipality: 'Cabo corrientes' },
    { id: '390', stablishment_name: 'Ipala', postal_code: '48419', municipality: 'Cabo corrientes' },
    { id: '391', stablishment_name: 'Ixtlahuahuey', postal_code: '48423', municipality: 'Cabo corrientes' },
    { id: '392', stablishment_name: 'La Ciénega', postal_code: '48426', municipality: 'Cabo corrientes' },
    { id: '393', stablishment_name: 'La Hermita', postal_code: '48400', municipality: 'Cabo corrientes' },
    { id: '394', stablishment_name: 'La Sauceda', postal_code: '48410', municipality: 'Cabo corrientes' },
    { id: '395', stablishment_name: 'Las Guásimas', postal_code: '48428', municipality: 'Cabo corrientes' },
    { id: '396', stablishment_name: 'Las Juntas del Tuito (Puente la Puchiteca)', postal_code: '48447', municipality: 'Cabo corrientes' },
    { id: '397', stablishment_name: 'Las Juntas y los Veranos', postal_code: '48425', municipality: 'Cabo corrientes' },
    { id: '398', stablishment_name: 'Llano de los Laureles', postal_code: '48400', municipality: 'Cabo corrientes' },
    { id: '399', stablishment_name: 'Llano Grande de Ipala', postal_code: '48416', municipality: 'Cabo corrientes' },
    { id: '400', stablishment_name: 'Los Corrales', postal_code: '48414', municipality: 'Cabo corrientes' },
    { id: '401', stablishment_name: 'Los Plátanos', postal_code: '48432', municipality: 'Cabo corrientes' },
    { id: '402', stablishment_name: 'Maito', postal_code: '48417', municipality: 'Cabo corrientes' },
    { id: '403', stablishment_name: 'Naranjitos (Arroyo Seco)', postal_code: '48417', municipality: 'Cabo corrientes' },
    { id: '404', stablishment_name: 'Paulo', postal_code: '48430', municipality: 'Cabo corrientes' },
    { id: '405', stablishment_name: 'Pedro Moreno', postal_code: '48426', municipality: 'Cabo corrientes' },
    { id: '406', stablishment_name: 'Peregrina de Gómez (La Boquita)', postal_code: '48419', municipality: 'Cabo corrientes' },
    { id: '407', stablishment_name: 'Potrerillos del Tuito', postal_code: '48432', municipality: 'Cabo corrientes' },
    { id: '408', stablishment_name: 'Provincia (Los Húmedos)', postal_code: '48445', municipality: 'Cabo corrientes' },
    { id: '409', stablishment_name: 'Quimixto', postal_code: '48424', municipality: 'Cabo corrientes' },
    { id: '410', stablishment_name: 'Santa Cruz del Tuito', postal_code: '48448', municipality: 'Cabo corrientes' },
    { id: '411', stablishment_name: 'Tehuamixtle (Tehualmixtle)', postal_code: '48417', municipality: 'Cabo corrientes' },
    { id: '412', stablishment_name: 'Villa del Mar', postal_code: '48419', municipality: 'Cabo corrientes' },
    { id: '413', stablishment_name: 'Yelapa', postal_code: '48422', municipality: 'Cabo corrientes' },
    { id: '414', stablishment_name: 'Zicatán', postal_code: '48413', municipality: 'Cabo corrientes' },
];

export default POSTAL_CODE;