export enum ShiftDayOperations {
    INVENTORY_OPERATION = 0,
    ROUTE_TRANSACTION = 1,
    ATTENTION_OUT_OF_ROUTE = 2,
    NEW_CLIENT_REGISTRATION = 3,
    ROUTE_CLIENT_ATTENTION = 4,
    ATTEND_CLIENT_PETITION = 5
}