const TABLES = {
  DAYS: 'days',
  FOLLOWED_PATHS: 'followed_paths',
  INVENTORY_OPERATION_TYPES: 'inventory_operation_types',
  INVENTORY_OPERATIONS: 'inventory_opertions',
  PRODUCTS: 'products',
  PRODUCT_OPERATION_DESCRIPTIONS: 'product_operation_descriptions',
  ROUTE_DAY_STORES: 'route_day_stores',
  ROUTE_DAYS: 'route_days',
  ROUTE_PATHS: 'route_paths',
  ROUTE_TRANSACTIONS_TYPES: 'route_transaction_types',
  ROUTE_TRANSACTIONS: 'route_transactions',
  ROUTE_TRANSACTION_OPERATIONS: 'route_transaction_operations',
  ROUTE_TRANSACTION_OPERATIONS_DESCRIPTONS: 'route_transaction_operation_descriptions',
  ROUTES: 'routes',
  STORES: 'stores',
  VENDORS: 'vendors',
  WORK_DAYS: 'work_days',
};
export default TABLES;
